ALTER TABLE T_GAEN_EXPOSED
    ADD COLUMN EXPIRY TIMESTAMP WITH TIME ZONE NOT NULL
;

CREATE INDEX IN_DPPPT_GAEN_EXPOSED_RECEIVED_AT
    ON T_GAEN_EXPOSED (RECEIVED_AT);

CREATE INDEX IN_DPPPT_GAEN_EXPOSED_EXPIRY
    ON T_GAEN_EXPOSED (EXPIRY);